language: node_js
deploy:
  provider: npm
  email: dylanalvarez1995@gmail.com
  api_key:
    secure: gOKqZT2I2uYLWNMJ0Z6SWuTVjMBiAQuAJjz78Mq63K3g70BZAI5WMr68tbLr1AdxyAkw/WiQPdJ7b10rWn7TIDpo3PpSetheaNnGh9tYnjFkqWeu/blMvi1B1Ruhc1bNO57YfdqbolLbrTGEGMzGj5TV/9kwWxRkBe8cj29NM018eQSMroQZDEHWD96q4Sa4NVq9ZJTnoTlgCSNQg7M2vXR1NnYAuHFIgXxwbtlvv5lwqRpsC+xzEIJdPuTnJQFUi2+FJBaATQ/16Y/KbxBd04nP3+07XYom61IJmg3U85ws6j+d2eZZoOODX0Fy53C4L5vA0GMyc68v/gn3YMZkXxxU2yS0hyWOEJGRHE79v9vnIo93QZZLP2mMQtSJ/Aqkxv63MdFjrN4vRK0NaxTfOK/uq6kqL+6Ij87FuHCweGQw73IOCNT26166g3KhtBDLZvkfZqYlZisyHDHxvQv883a3HjmcRmeWJzyTzY537eDi7jX6FW/KSUq2Oo2+Mjy4qmKbqOIFCqP+xnEgsda3LZfqPeKxGJbE0LqR7OUGEDCPg0b2wnt2RHYNjqBccaG+3d6INMl1QXQyM7/7eHSA7sr8ksd86equQJ3+5t1H1Z5sxOroI35tkGAVsmbtEFZUGPrEg5K6auSoqUD7C57Q4MNjGrt4DQT34muFBcHMTio=
